### ISSUE TITLE
Display edge labels by default

### ISSUE THREAD

**Issue by ryotayamanaka** [g2glab/hellograph#1]
and/or the selection at the "Controls" should be saved in the cookie?

**Comment by shota-matsumoto-lm** [comment]
> and/or the selection at the "Controls" should be saved in the cookie?

I agree. I will implement such feature in the next chance.

**Comment by ryotayamanaka** [comment]
This commit is for vertices. 1fc1cf47d6a46cc651640deda7f22575d204f168

Thanks!
