### ISSUE TITLE
Edges are not highlighted when focused in the Edit panel

### ISSUE THREAD

**Issue by ryotayamanaka** [g2glab/hellograph#24]
When an edge is focused in the Edit panel, the View panel moves to the edge but the edge is not highlighted. (The nodes and edges in the previous focus are still highlighted.)

![Screen Shot 2021-06-14 at 1 35 46](https://user-images.githubusercontent.com/4862919/121815335-ed270580-ccb0-11eb-9a19-6cbac22d9cd9.jpg)
![Screen Shot 2021-06-14 at 1 35 55](https://user-images.githubusercontent.com/4862919/121815336-f021f600-ccb0-11eb-9d59-a7fbd6d8c23a.jpg)

**Comment by shota-matsumoto-lm** [comment]
I fixed this bug in the commit 662801650e8a3648ea0e55ced03a328a9b929942. Could you check it?

**Comment by ryotayamanaka** [comment]
Thank you!
