### ISSUE TITLE
I would like to use initialize option for the config. (usability suggestion)

### ISSUE THREAD

**Issue by yuuur** [g2glab/hellograph#25]
I would like to use initialize option for the config. 
If we make a defective code on the config section, the drawing fails, and fixing it to the normal state can be bothersome. It would be comfortable to use the tool if we have some initialization button to fix some issues just by clicking it.
(usability suggestion)

**Comment by ryotayamanaka** [comment]
Thank you for the suggestion.

We should consider:

- adding "reset" button
- reset the config only? pg data together? or separate buttons?

**Comment by yuuur** [comment]
As a first step, just adding the "reset" config button for formatting sounds fine. As for the layout, moving the config button to the left and adding the reset formatting button below the config icon looks nice to me so as not to hide the code. 

![image](https://user-images.githubusercontent.com/74803050/122401903-fa493a80-cfb7-11eb-99c5-bdfc01957cf8.png)

**Comment by ryotayamanaka** [comment]
Fixed at 5c40433d06cf38eefc1d9de5f9adbdd23948f2fb. Thank you for your suggestions!

**Comment by ryotayamanaka** [comment]
Fixed at 5c40433. Thank you for your suggestions!
