### ISSUE TITLE
I would like to use the multiple edges feature 

### ISSUE THREAD

**Issue by yuuur** [g2glab/hellograph#26]
The code that I tried did not work for the multiple edges.
 I didn't get the desirable result (both edges can be shown) rather, only the latter edge (label2) shown. 

        A :person 
        B :person
        A -> B :Label1
        A -> B :Label2

This happens both on Firefox and Chrome.

![image](https://user-images.githubusercontent.com/74803050/122031462-b1538380-ce09-11eb-97e5-134d065bc1d1.png)

**Comment by ryotayamanaka** [comment]
PG format accepts multi-edges in that syntax, so those edges should be drawn as separate edges.

However, hellograph currently shows only the last one in the editor (just as the duplicate definition of the nodes in the same IDs).

We would like to enhance. Thank you!

**Comment by ryotayamanaka** [comment]
Enhanced at 43dcf8efe199082118754160437e0049d1128164. Thank you!
