### ISSUE TITLE
request to use the : mark in property 

### ISSUE THREAD

**Issue by yuuur** [g2glab/hellograph#32]
When it comes to using the time, the notation on the console should be written as follows.

> time:"21:30" 

I'd say If we can express just like 

> time:21:30

, it enhances usability.

**Comment by ryotayamanaka** [comment]
Thank you.

We should discuss if we can allow this syntax. The rendering error by this should be fixed anyway.

**Comment by ryotayamanaka** [comment]
Directions:

- `:` should be allowed in property values even if not quoted
- The syntax error should be handled properly (showing a message..?) in general

**Comment by ryotayamanaka** [comment]
@yuuur `:` is now allowed, please try!

**Comment by ryotayamanaka** [comment]
The syntax error hightlight is added at 83951a5280eac01aa30383219cec976dae49483f
