### ISSUE TITLE
PG Syntax Highlighting - String IDs

### ISSUE THREAD

**Issue by ryotayamanaka** [g2glab/hellograph#6]
String IDs are not properly highlighted.

![Screen Shot 2021-04-29 at 15 57 02](https://user-images.githubusercontent.com/4862919/116512801-8b2e5e80-a903-11eb-9f1c-97dc537ecbc1.jpg)

```
101 :label_01 name:101
abc :label_02 name:abc      # No color for string IDs
G2G :label_03 has_name:true # Partially colored
102 :label_04 invalid_item  # White color for invalid items?
abc -> G2G :label_05        # Same in edges
```

**Comment by ryotayamanaka** [comment]
It seems inline comments are problematic now. It used to work fine.

```
I :person name:"your name" # Comment
```

**Comment by ryotayamanaka** [comment]
Also, node/edge IDs in double-byte characters are not highlighted:

```
I :person English:"your name"
私 :人 日本語:私の名前
ผม :คน ไทย:ผมชื่อ
I -> 私 :same_as
I -> ผม :same_as
```
![Screen Shot 2021-05-05 at 12 31 50](https://user-images.githubusercontent.com/4862919/117094114-de8a2c00-ad9d-11eb-8aa1-84e24c3b5aa5.jpg)

**Comment by ryotayamanaka** [comment]
Decided that the inline comment like below should not be allowed, so far.
```
I :person name:"your name" # Comment
```

**Comment by shota-matsumoto-lm** [comment]
Fixed by [fd0fa5](https://github.com/g2glab/hellograph/commit/fd0fa5489099bc64830da008e338a4515f3361c1) and [cd9718](https://github.com/g2glab/hellograph/commit/cd97180bbd147e5f3d3fd363f925f31117b9ba66).
